# Generated by Django 5.1.2 on 2024-10-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_cantidadminima'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidadMedida',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('U', 'Unidades')], max_length=4),
        ),
    ]
