# Generated by Django 5.1.2 on 2024-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='domicilioNum',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
