# Generated by Django 5.1.2 on 2024-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True),
        ),
    ]
