# Generated by Django 5.1.2 on 2024-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_materiaprima_cantidadminima'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_recibido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
