# Generated by Django 5.1.2 on 2024-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_estado_recibido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcionpedido',
            name='monto_total',
        ),
        migrations.AlterField(
            model_name='recepcionpedido',
            name='fecha_recepcion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recepcionpedido',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
