# Generated by Django 5.1.2 on 2024-10-20 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_mayorista', '0001_initial'),
        ('empleado', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField()),
                ('fecha_venta', models.DateTimeField()),
                ('tipo_venta', models.CharField()),
                ('forma_pago', models.CharField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(max_length=500)),
                ('cliente_mayorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_cliente_mayorista', to='cliente_mayorista.clientemayorista')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_empleado', to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_venta_producto', to='producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_venta', to='venta.venta')),
            ],
        ),
    ]
