# Generated by Django 5.1.2 on 2024-10-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Efectivo', 'Efectivo')]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_cliente',
            field=models.CharField(choices=[('Mayorista', 'Mayorista'), ('Final', 'Consumidor final')]),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Crédito')]),
        ),
    ]
