# Generated by Django 5.1.2 on 2024-10-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('cuit', models.CharField(max_length=13, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_incorporacion', models.DateField()),
                ('domicilio_calle', models.CharField(max_length=100)),
                ('domicilio_numero', models.IntegerField()),
                ('domicilio_localidad', models.CharField(max_length=50)),
                ('domicilio_departamento', models.CharField(max_length=50)),
            ],
        ),
    ]
